name: Azure CLI

on:
  workflow_dispatch:
    
jobs:
  azure-cli-commands:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run az commands'
        shell: pwsh
        run: |
          $keyvault_token=Get-AzKeyVaultSecret -VaultName testkeyvaultsai  -AsPlainText -Name github-tm-spn-secret
          az login --service-principal -u dcc35921-6a69-4b62-bd4f-a68324a88844 -p $keyvault_token --tenant 20f3b949-2903-4d24-9d01-ad8df676e397
