name: Azure CLI

on:
  workflow_dispatch:
    
jobs:
  azure-cli-commands:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run az commands'
        shell: pwsh
        run: |
          
          $kv_key_spn_id=az keyvault secret show --name github-tm-spn-spn-id --vault-name testkeyvaultsai1 --query value -o tsv
          $kv_spn_secret=az keyvault secret show --name github-tm-spn-secret --vault-name testkeyvaultsai1 --query value -o tsv
          az login --service-principal -u $kv_key_spn_id -p $kv_spn_secret --tenant 20f3b949-2903-4d24-9d01-ad8df676e397
          az account set --subscription ef16b033-ec3e-4659-b1b7-1532f58b43e3
          
          #az postgres server create --name mypgsvr-eu --resource-group dev-rg --location "East US2" --admin-user saikiran545 --admin-password Pbjljs6#! --sku-name GP_Gen5_2
          #az postgres server replica create --name replica-cenus-pgsvr-replica --source-server mypgsvr-eu --resource-group dev-rg --location CentralUS
          az network private-endpoint create --name privaceratestreppe --resource-group dev-rg  --vnet-name privacera-vnet  --subnet privacera-subnet1  --private-connection-resource-id $(az resource show -g dev-rg -n replica-cenus-pgsvr --resource-type "Microsoft.DBforPostgreSQL/servers" --query "id" -o tsv)  --group-id postgresqlServer  --connection-name testrepconnection 
          
          
          #az storage account failover -n mystoragefailover -g terraform-rg --yes
          #az storage account update --name mystoragefailover --resource-group terraform-rg --sku Standard_GRS
          #az cosmosdb failover-priority-change --name testcosmosdb-sai  --resource-group terraform-rg --failover-policies "East US2=2" "CentralUS=0" 
          










