name: Azure CLI

on:
  workflow_dispatch:
    
jobs:
  azure-cli-commands:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run az commands'
        shell: pwsh
        run: |
          
          $kv_key_spn_id=az keyvault secret show --name github-tm-spn-spn-id --vault-name testkeyvaultsai --query value -o tsv
          $kv_spn_secret=az keyvault secret show --name github-tm-spn-secret --vault-name testkeyvaultsai --query value -o tsv
          az login --service-principal -u $kv_key_spn_id -p $kv_spn_secret --tenant 20f3b949-2903-4d24-9d01-ad8df676e397
          az account set --subscription ef16b033-ec3e-4659-b1b7-1532f58b43e3
          #az storage account failover -n mystoragefailover -g terraform-rg --yes
          #az storage account update --name mystoragefailover --resource-group terraform-rg --sku Standard_GRS
          az cosmosdb failover-priority-change --failover-policies CentralUS=0  --name testfailovercosmos  --resource-group terraform-rg










