name: Azure CLI

on:
  workflow_dispatch:
    
jobs:
  azure-cli-commands:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run az commands'
        shell: pwsh
        run: |


           az login --service-principal -u b471c45c-3580-4c25-a34d-f11a87e52dd0 -p AKu8Q~tAbPifCgLaRfWi5pyAQd.IGcSxZI21RaTf --tenant 78959ae4-3fb1-4d7b-8e35-f92abe2324e4
           az account set --subscription fc04db5f-6926-4ff0-acbd-06d24a5ffdb2
           az postgres server create --name mypgsvr-eu --resource-group dev-rg --location "East US2" --admin-user saikiran545 --admin-password Password@1234! --sku-name GP_Gen5_2
           az postgres server replica create --name replica-cenus-pgsvr-replica --source-server mypgsvr-eu --resource-group dev-rg --location CentralUS
          
          #$kv_key_spn_id=az keyvault secret show --name github-tm-spn-spn-id --vault-name testkeyvaultsai2 --query value -o tsv
          # $kv_spn_secret=az keyvault secret show --name github-tm-spn-secret --vault-name testkeyvaultsai2 --query value -o tsv
          # az login --service-principal -u $kv_key_spn_id -p $kv_spn_secret --tenant 20f3b949-2903-4d24-9d01-ad8df676e397
          # az account set --subscription ef16b033-ec3e-4659-b1b7-1532f58b43e3
          
          #az postgres server create --name mypgsvr-eu --resource-group dev-rg --location "East US2" --admin-user saikiran545 --admin-password Pbjljs6#! --sku-name GP_Gen5_2
          #az postgres server replica create --name replica-cenus-pgsvr-replica --source-server mypgsvr-eu --resource-group dev-rg --location CentralUS
          #az network private-endpoint create --name privaceratestreppe --resource-group dev-rg  --vnet-name privacera-vnet  --subnet privacera-subnet1  --private-connection-resource-id $(az resource show -g dev-rg -n replica-cenus-pgsvr --resource-type "Microsoft.DBforPostgreSQL/servers" --query "id" -o tsv)  --group-id postgresqlServer  --connection-name testrepconnection 
          
          #az network private-dns zone create --resource-group dev-rg --name  "privatelink.postgres.database.azure.com" 
          #az network private-dns link vnet create --resource-group dev-rg --zone-name  "privatelink.postgres.database.azure.com" --name myprivatelink  --virtual-network privacera-vnet --registration-enabled false
          #az resource show --ids /subscriptions/ef16b033-ec3e-4659-b1b7-1532f58b43e3/resourceGroups/dev-rg/providers/Microsoft.Network/networkInterfaces/privaceratestreppe.nic.535c9126-5f62-4450-931a-ba32161c34ac --api-version 2019-04-01 -o json
          
          #az network private-endpoint dns-zone-group add --endpoint-name privaceratestreppe -g dev-rg -n default --zone-name privatelink.postgres.database.azure.com --private-dns-zone /subscriptions/ef16b033-ec3e-4659-b1b7-1532f58b43e3/resourceGroups/dev-rg/providers/Microsoft.Network/privateDnsZones/privatelink.postgres.database.azure.com
          #az network private-dns record-set a create --name replica-cenus-pgsvr --zone-name privatelink.postgres.database.azure.com --resource-group dev-rg  
          #az network private-dns record-set a add-record --record-set-name replica-cenus-pgsvr --zone-name privatelink.postgres.database.azure.com --resource-group dev-rg -a 10.82.1.197
          
          
          #az storage account failover -n mystoragefailover -g terraform-rg --yes
          #az storage account update --name mystoragefailover --resource-group terraform-rg --sku Standard_GRS
          #az cosmosdb failover-priority-change --name testcosmosdb-sai  --resource-group terraform-rg --failover-policies "East US2=2" "CentralUS=0" 
          










